name: Translate README

on:
  push:
    branches:
      - main
      - master

jobs:
  translate_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      # Crea la cartella docs se non esiste
      - name: Create docs directory
        run: mkdir -p docs
      
      # Traduci e sposta i file
      - name: Translate to Italian
        uses: dephraiim/translate-readme@main
        with:
          LANG: it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Move Italian README
        run: mv README.it.md docs/
      
      # Ripeti per le altre lingue
      - name: Translate to French
        uses: dephraiim/translate-readme@main
        with:
          LANG: fr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Move French README
        run: mv README.fr.md docs/
      
      # Aggiungi qui le altre lingue necessarie...
      
      # Aggiorna i link delle bandiere
      - name: Update language links
        run: |
          sed -i 's|/README.md|../README.md|g' docs/README.*.md
          sed -i 's|/docs/README|./README|g' docs/README.*.md
      
      # Commit e push delle modifiche
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-translate READMEs" && git push)
